[builder][FIX] XMLTemplateAnalyzer: Throws on tags without attributes (https://github.com/SAP/ui5-builder/pull/322)
When processing XML tags with no attributes, getAttributeNS caused an Error like this:
```
TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at getAttributeNS
```